### ISSUE TITLE
2.0: UI - After removing a repo, the page redirects back to the repo that was removed.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1002]
![Screen Shot 2018-11-26 at 10:46 PM](http://marker.screenshots.prod.s3.amazonaws.com/77f8b49795564e699aa9d0a4bc400698-1543272362739.png)

**Summary:**
After removing an added repo and removing, the UI redirects to the repo that was removed. This throws a 404 when using docker-compose. The attached screenshot shows what happens when you do this when running manually.
**Steps to Reproduce:** 
1. Add a repo to the Service Catalog
2. Remove the added repo.
**Expected Results:** 
The page is redirected to the Supergiant repo
**Actual Results:** 
The page is not redirected to the Supergiant repo
(You can see this in the url in your browser)

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/catalog/ewh](http://localhost:4200/catalog/ewh)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by nikage** [comment]
fixed in #1018
