### ISSUE TITLE
2.0: UI - AWS cluster creation should have an option to multi-az

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1008]
![Screen Shot 2018-11-27 at 3:13 PM](http://marker.screenshots.prod.s3.amazonaws.com/923f20b0daa44031b82db6779081e09e-1543331634933.png)

**Summary:**
Cluster creation in AWS needs to have an option (possibly checkbox) to provision as multi-az. This option should also default to multi-az.

If the user unchecks or unselects this option, the user is able to choose an az.

**Notes:** 
Please reference #991  for backend changes.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
closed via https://github.com/supergiant/control/pull/1096
