### ISSUE TITLE
2.0.1: API - Place SSH public keys in ubuntu and kubeconfig in root

### ISSUE THREAD

**Issue by TheKLARKEN** [supergiant/control#1011]
**Short Summary:**
When SSHing into an SG Control cluster, you must then change user to `ubuntu` to use `kubectl`.

**Steps to Reproduce:**
1. Make a cluster, SSH into `root`. Try to use `kubectl`. It won't work.
2. Make a cluster, SSH into `ubuntu`. It won't work.

**Expected Results:**
To be able to use `kubectl` more easily.

**Actual Results:**
Extra steps are needed for users to start messing with their clusters.

**Dev Info:** (add links to log files)
1. Output of `go version`: `go version go1.10.2 darwin/amd64`
2. Commit hash or release tag used (`git log`): `80629ef0dcc1a72f7b2b968991b50fe9a404b93f`
3. Number of Masters and Nodes: 1M 2N
4. Cloud Provider: AWS

**Comment by stgleb** [comment]
Resolved
