### ISSUE TITLE
2.0.1: API - `/opt/bin/helm` Helm should be added to `PATH`

### ISSUE THREAD

**Issue by TheKLARKEN** [supergiant/control#1012]
**Short Summary:**
When users SSH into their cluster, they might try to use `helm` and not find it. They would either need to search the docs or the source code to find out where it is, and this should not be so complex. Helm should be usable immediately upon SSHing into a cluster.

**Steps to Reproduce:**
1. Make a cluster on AWS
2. SSH into it as `root`
3. Run `helm`
4. Change user to `ubuntu`
5. Run `helm`

**Expected Results:**
This:

```
The Kubernetes package manager

To begin working with Helm, run the 'helm init' command:

	$ helm init
...
```

**Actual Results:**

```
helm: command not found
```

**Dev Info:** (add links to log files)
1. Output of `go version`: `go version go1.10.2 darwin/amd64`
2. Commit hash or release tag used (`git log`): `80629ef0dcc1a72f7b2b968991b50fe9a404b93f`
3. Number of Masters and Nodes: 1M 2N
4. Cloud Provider: AWS

**Comment by eldridgeh** [comment]
Closing due to helm being set to /usr/bin
