### ISSUE TITLE
AWS multi master networking is broken

### ISSUE THREAD

**Issue by stgleb** [supergiant/control#1022]
**Short Summary:**

Quote 

```
Instances in the same security group will not be able to connect to each other out of the box
```
Master nodes in cluster needs to communicate - etcd  management port.
So AWS multi master cluster will be broken because nodes of etcd don't see
each other and never gets to consensus.

**Steps to Reproduce:**

1. Create cluster in AWS with three nodes
2. ssh to one node and try to ping, curl or whatever another node

**Expected Results:**

Ping, ssh, curl will work fine

**Actual Results:**

It doesn't work

Reproduces on current master

**Comment by gopherstein** [comment]
This is a duplicate with this existing ETCD issue. https://github.com/supergiant/control/issues/864
