### ISSUE TITLE
2.0.1: UI - Service Catalog add/remove buttons 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1023]
![Screen Shot 2018-11-27 at 9:58 PM](http://marker.screenshots.prod.s3.amazonaws.com/8dd120ef06f6455d9d5b714dee873948-1543355926200.png)

**Summary:**
Service Catalog add/remove buttons need vetting. They are two different sizes and possibly the remove button color may need to be changed.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:8080/catalog/supergiant](http://localhost:8080/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1653 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
It's a design issue, I would like to resolve such issues with accordance to design specs. Also, this referencing to other issues like https://github.com/supergiant/control/issues/1058, where I asked to change order of this buttons and margins.

In this particular situation I don't like logic of this tile with these 2 action buttons, and I have assigned a task to re-design it to myself (@egopher promised to include this task to roadmap). 

**As a quick solution** I propose to change buttons to links with icons, e.g.:
[+] add repo
[-] remove repo
and change solid border of tile to dashed

@eldridgeh @nikage @josephkane

**Comment by hetmanchuk** [comment]
**A quick solution:**
![screen shot 2019-01-02 at 2 01 14 pm](https://user-images.githubusercontent.com/11389252/50597070-ce50a200-0eae-11e9-9d99-7e9e1da71ea0.png)

**Taras Hetmanchuk [2:10 PM]**
Honestly, this is not my idea to put actions on tile. I would prefer to put actions under or/and above tiles. @joe @Nick what do you think?

**Nick [2:18 PM]**
To me it’s not a cool idea to put actions on the card which is supposed to be an app

**Joe Kane [4:36 PM]**
I also dont like the actions on a tile (like, REALLY don’t like). @Taras re: logos, how will we tell if the logos need to be horizontal in the first place? Or will they all be horizontal?

**Comment by josephkane** [comment]
@nikage @hetmanchuk can we close this issue in favor of a overall service catalog redesign?

**Comment by eldridgeh** [comment]
Closing as it is no longer relevant.
