### ISSUE TITLE
2.0: API update node status after joining a cluster

### ISSUE THREAD

**Issue by saheienko** [supergiant/control#1034]
**Describe the bug**
After adding a node to a cluster it's state is shown as `Provisioning` after joining a cluster.

```root@test-do-master-0ec9:~# kubectl get no
NAME                    STATUS    ROLES     AGE       VERSION
test-do-master-0ec9   Ready     <none>    1h        v1.11.1
test-do-node-9c97     Ready     <none>    48m       v1.11.1
```

```
 "nodes": {
  "test-do-node-9c97": {
    "id": "120920900",
    "taskId": "9c978e4c-8e1a-4e20-8146-83b694935986",
    "role": "node",
    "createdAt": 0,
    "provider": "digitalocean",
    "region": "ams3",
    "size": "1gb",
    "publicIp": "174.138.12.4",
    "privateIp": "10.133.81.247",
    "state": "provisioning",
    "name": "test-do-node-9c97"
  }
}
```
name	test-do-node-9c97

**To Reproduce**

1. Deploy a cluster.
2. Add a node to it.
3. Log in to the master node and wait until the node joins a cluster.
4. Check node's state on the UI cluster page.

**Expected behavior**
Node with a `Running` state.

**Additional context**

**Comment by gopherstein** [comment]
@saheienko We are unable to reproduce this on digital ocean. Is this still an issue?

**Comment by saheienko** [comment]
@gopherstein yep, not it is showing a proper state.
Closing the issue.
