### ISSUE TITLE
2.0: UI - Swap buttons "Cancel & OK" and fix margin on confirmation window

### ISSUE THREAD

**Issue by hetmanchuk** [supergiant/control#1058]
![image](https://user-images.githubusercontent.com/11389252/49226733-16802e80-f3f0-11e8-8bce-5fa78ba6d9c7.png)

This is **low priority** fix.

**Short Summary:**
Swap position of buttons "Cancel" and "OK" ("Cancel should be first") and fix margin between them (should be 16 pixels) on all conformation windows.

**Steps to Reproduce:**
1. Create cluster with minimum 2 nodes
2. Go to cluster details page
3. Hit trash icon in table with clusters

**Expected Results:**
All notifications (delete node, cluster, app, etc) implemented with the same style and according to design specs, be sure that "Cancel" button located before "Delete" or other action.

@josephkane @nikage

**Comment by eldridgeh** [comment]
Closing due to no longer being relevant.
