### ISSUE TITLE
2.0: UI - Add "close" icon on Terminal window

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1062]
![Screen Shot 2018-11-29 at 4:46 PM](http://marker.screenshots.prod.s3.amazonaws.com/4fc15297e4614b069789be0b6057f585-1543509981441.png)

**Summary:**
Some users could be confused because there are no close icon or button.

**Steps to Reproduce:** 
1. Create cluster
2. While creating cluster hit second icon on the right top corner on table ()

**Expected Results:** 
Users can close modal window with [X] icon

**Actual Results:** 
Users can close window only by clicking on canvas outside modal window or by [ESC] key

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/clusters/e08cb75c](http://localhost:4200/clusters/e08cb75c)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@hetmanchuk can this be closed?

**Comment by hetmanchuk** [comment]
@josephkane I can't see on the latest updates, could you post a screenshots? Also, is it possible to put this close icon on every similar modal (some screenshots in attach)?
<img width="1128" alt="screen shot 2018-12-20 at 2 14 27 pm" src="https://user-images.githubusercontent.com/11389252/50284570-12c95000-0462-11e9-8a60-512af8898e5d.png">
<img width="893" alt="screen shot 2018-12-20 at 2 14 11 pm" src="https://user-images.githubusercontent.com/11389252/50284571-12c95000-0462-11e9-9f19-f23e3f356249.png">
<img width="748" alt="screen shot 2018-12-20 at 2 14 02 pm" src="https://user-images.githubusercontent.com/11389252/50284573-1361e680-0462-11e9-9464-ca4b781fd3a3.png">
<img width="712" alt="screen shot 2018-12-20 at 2 13 38 pm" src="https://user-images.githubusercontent.com/11389252/50284574-1361e680-0462-11e9-871b-e7771986881e.png">

**Comment by josephkane** [comment]
@hetmanchuk 
sure thing, will add in separate PR
![image](https://user-images.githubusercontent.com/18269936/50294460-8f950380-043b-11e9-99ef-bd56af0f1c73.png)

**Comment by josephkane** [comment]
closed via https://github.com/supergiant/control/pull/1215

**Comment by josephkane** [comment]
closed via https://github.com/supergiant/control/pull/1215

**Comment by hetmanchuk** [comment]
@josephkane thanks!
