### ISSUE TITLE
2.0: API - Cluster State is not updated when restarting failed tasks

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1064]
![Screen Shot 2018-11-29 at 5:02 PM](http://marker.screenshots.prod.s3.amazonaws.com/4b4fd9e85e3c4806a36413ce6463d19b-1543510946441.png)

**Summary:**
When restarting a failed task (on a failed cluster), the task restarts fine but the cluster status is not updated in the database
**Steps to Reproduce:** 
Spin up a cluster, make it fail, restart tasks
**Expected Results:** 
cluster state should change from "failed" to "provisioning"
**Actual Results:** 
cluster state remains on "failed," showing warning in UI
**Notes:**

---
### More Info

**Reported by:** Joe Kane (joe@qbox.io)
**Source URL**: [http://localhost:4200/clusters/347dd436](http://localhost:4200/clusters/347dd436)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 971</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by eldridgeh** [comment]
@josephkane Is this related to #966 ?
If so, I will close the old one.

**Comment by josephkane** [comment]
@eldridge I think it is. We should talk and consolidate both of these to one

**Comment by gopherstein** [comment]
Closing as this is a duplicate. Lets rais the priority on the other one if needed.
