### ISSUE TITLE
2.1: API - Create Subnet causes error in AWS

### ISSUE THREAD

**Issue by stgleb** [supergiant/control#1069]
When use non default subnet in AWS provisioning SG creates new subnet,
but required parm Subnet CIDR is not passed to SG from UI

```
validation error(s) found.\n- missing required field, CreateSubnetInput.CidrBlock.\n: aws: create subnet
```

**Comment by eldridgeh** [comment]
@stgleb Is this still an issue?

**Comment by stgleb** [comment]
No, it is resolved

**Comment by stgleb** [comment]
No, it is resolved

**Comment by eldridgeh** [comment]
closing due to being resolved.
