### ISSUE TITLE
2.1: UI - Current UI do not allow to leave SubnetID empty to let SG create Subnet

### ISSUE THREAD

**Issue by stgleb** [supergiant/control#1070]
When provision cluster on AWS there is no way to create security group for cluster.

New security group gets created only when SubnetID is empty, but it is prohibited on the UI to have this
field empty. This forces user to use either default or existing subnet which is bad for deletion of resources - dependencies between those resources are uncontrolled.

**Comment by josephkane** [comment]
@stgleb if the UI removed the required flag from this field, would that fix this issue? and if so, should it default to blank?

**Comment by josephkane** [comment]
@stgleb can we close this?
