### ISSUE TITLE
2.0.1: UI – CATALOG —> Make fixed header longer and move filter to the center

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1094]
![Screen Shot 2018-12-03 at 1:14 PM](http://marker.screenshots.prod.s3.amazonaws.com/b979823119cf4e9298bf68fe8ac43db7-1543842850254.png)

**Summary:**
1. Fix title, filter, submenu (and add taller black gradient on the background)
2. Move "filter" input to the global center/middle of the page 

**Steps to Reproduce:** 
1. Spin up minimum 1 cluster
2. Got to Catalog from the top menu
3. Open one of the displayed charts/apps

**Notes:**

Hi-fid prototype: https://xd.adobe.com/view/1fe0bbb7-101c-4bc6-4e97-4178834c91ee-69d1/screen/a0478d4a-7625-4596-a31d-8926e4c27a27/sg2-apps-list-sg?fullscreen

Design specs: https://xd.adobe.com/spec/3c5108bd-fd7f-467f-47f8-837ef0d07611-4a60/screen/a0478d4a-7625-4596-a31d-8926e4c27a27/sg2-apps-list-sg/

P. S. I suppose layout has been changed when Joe fixed other issue.

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
<img width="835" alt="catalog_fixed_header2" src="https://user-images.githubusercontent.com/11389252/49382686-bbb44300-f71f-11e8-814b-9cc336ed1b82.png">
Also, please pay attention to the margin around the filter input.
