### ISSUE TITLE
2.0.1: UI – Top menu should be centered

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1102]
![Screen Shot 2018-12-03 at 3:29 PM](http://marker.screenshots.prod.s3.amazonaws.com/c696f58e6c024b6f9ad8838a29c49e5a-1543850959023.png)
---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by nikage** [comment]
close in #1125
