### ISSUE TITLE
2.0.1: UI - Adding a node should show Tasks and Logs for the new node

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1103]
![Screen Shot 2018-12-03 at 4:18 PM](http://marker.screenshots.prod.s3.amazonaws.com/5730eb16f0b64d7ba08409c2839566c9-1543853935781.png)

**Summary:**
When adding a node to an existing cluster, we currently do not display any of the tasks or logs while the new node is provisioning. 
**Steps to Reproduce:** 
1. Spin up a cluster
2. Add a node
**Expected Results:** 
When adding a node, the user is redirected to the Cluster details page at the node level.
The user is able to see in the machines section the ongoing tasks and logs as the node is provisioned. Just like they do when creating the cluster.
**Actual Results:** 
A node is added and the user does not see any task or logs.
**Notes:**
Adding a node currently returns a 200, it needs to return a 202 instead.
If you have any questions, please ask.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/7dd65dfc](http://localhost:4200/clusters/7dd65dfc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1020</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by nikage** [comment]
@gopherstein  @hetmanchuk is there additional design supposed to this feature?

**Comment by josephkane** [comment]
@hetmanchuk 
![image](https://user-images.githubusercontent.com/18269936/49442791-2ac98000-f790-11e8-81bf-c4b939b29876.png)
