### ISSUE TITLE
2.0: UI - Change "Home Page" to "Homepage" in footer

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1114]
![Screen Shot 2018-12-04 at 11:03 AM](http://marker.screenshots.prod.s3.amazonaws.com/2e452c75771245d5929ba94947015296-1543921410176.png)

https://english.stackexchange.com/questions/112038/home-page-or-homepage

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1379 x 867</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
Done 
https://github.com/supergiant/control/pull/1115

**Comment by gopherstein** [comment]
https://github.com/supergiant/control/pull/1115
