### ISSUE TITLE
2.0: API - AWS - A cluster task needs to be created to create a secret with AWS creds.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#1123]
**Short Summary:**
On AWS cluster creation, a task needs to be made so that a secret is made in the cluster that contains the AWS cloud provider access key and secret key so that they can be used as env variables.

**Expected Results:**
The secret should have a name of:
name: awsconnect
The secret should have key values as:
accesskey: xxxxxxxx
secretkey: xxxxxxxxx

https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#convert-your-secret-data-to-a-base-64-representation

**Comment by gopherstein** [comment]
We might have a more automated solution for this. Closing this issue for now, and we will re-open if this feature is needed.
