### ISSUE TITLE
2.0: API - We are no longer getting inline metrics on AWS

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1127]
![Screen Shot 2018-12-04 at 8:08 PM](http://marker.screenshots.prod.s3.amazonaws.com/d6d60fed1b6147ab92cb754d07597d7c-1543954096779.png)

**Summary:**
After deploying an AWS cluster, we are no longer getting the inline cluster metrics in the machine table on the clusters details page.

**Steps to Reproduce:** 
1. Spin up a cluster in AWS
2. After the cluster is created, wait 10-20 minutes.
**Expected Results:** 
After waiting for a few minutes, the CPU and RAM metrics show up in the machines table.
**Actual Results:** 
The inline metrics for each machine do not show up, however, the total cluster metrics does.
**Notes:**
I have attached what is being returned in the image below. @josephkane says this is returning the incorrect data.
<img width="673" alt="screen shot 2018-12-04 at 2 04 37 pm" src="https://user-images.githubusercontent.com/35240784/49469816-1ad09100-f7ce-11e8-97d0-20792dad81ac.png">

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/9b95b67a](http://localhost:4200/clusters/9b95b67a)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1020</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by stgleb** [comment]
This is because aws changes keys for metric map after some amount of time. Work on that.
