### ISSUE TITLE
2.0: - docker-compose file needs vetting

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#1132]
**Short Summary:**
The docker-compose.yaml file is not building the UI.
**Expected Results:**
The docker-compose should always have the most recent UI changes when it is ran
**Actual Results:**
The docker-compose does not build the UI correctly

**Comment by taaraora** [comment]
#1134

**Comment by eldridgeh** [comment]
This fix has been merged. @taaraora Please reference the issues in the PR's so that issues will close when the PR is merged.
