### ISSUE TITLE
2.0.1: UI - Make all header (H1–h4) font weights bolder

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1140]
![Screen Shot 2018-12-05 at 1:09 PM](http://marker.screenshots.prod.s3.amazonaws.com/f108f19cee3e480d8c508260332a2855-1544015363935.png)

![image](https://user-images.githubusercontent.com/11389252/49515123-a74a8480-f89e-11e8-80b7-da3cfe7de7bd.png)

![image](https://user-images.githubusercontent.com/11389252/49515163-d3fe9c00-f89e-11e8-844c-f48e16ef42fa.png)

**Short Summary:**
Users complaining on very thin fonts in headers, examples in attachments. All thin headers should be changed to bolder ones.

**Steps to Reproduce:**
1. Spin up 1 cluster
2. Go to cluster details page or Service Catalog

**Expected Results:**
Header fonts are more readable and not too thin (size: 300)

**Actual Results:**
Header fonts are very thin (size: 100)

**Specs:**
https://xd.adobe.com/spec/3c5108bd-fd7f-467f-47f8-837ef0d07611-4a60/screen/6ea8ae91-0890-451a-98ec-9fe16fb19f0a/sg2-apps-list-verified/
https://qboxio.atlassian.net/wiki/spaces/SG/pages/724566019/Design+Specs+Style+Guide

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 867</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
I noticed during previous slices that there was a definite discrepancy between the xD font weight ("Regular", "Bold", etc) and the Google Font weights. I don't think this fix will be as simple as universal styles on all headlines as a result. Not a huge deal obviously, but this will have to be more surgical than universal.

**Comment by hetmanchuk** [comment]
@josephkane Thanks Joe, I will find and replace 100 weight to 300 in CSS on all headers (I've tested ir locally and it looks well). Yep, this is more surgical ;)

**Comment by hetmanchuk** [comment]
@gopherstein, close this issue, please.

**Comment by josephkane** [comment]
closed via https://github.com/supergiant/control/pull/1204
