### ISSUE TITLE
2.0.1: API - AWS Keypair and VPC's are not always deleted

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#1144]
**Short Summary:**
When deleting a multi AZ cluster, vpc's and keypairs do not look to always get deleted.
**Steps to Reproduce:**
1. Create a multi AZ cluster in eu-west-1
2. Create two masters in separate az's
3. Create two nodes in separate az's
4. Once the cluster is created, open up the the AWS console and find the keypair and vpc's  sections in the aws console.
5. Locate the keypair and vpc id from the master details page
6. Search for the keypair and vpcid in the AWS console sections
**Expected Results:**
When the cluster is deleted, it completely cleans up after itself.
**Actual Results:**
Not all resources are always cleaned up.
**Dev Info:** (add links to log files)
1. Output of `go version`: 1.10
2. Commit hash or release tag used (`git log`): https://github.com/supergiant/control/pull/1138
3. Number of Masters and Nodes: 2 master 2 nodes
4. Cloud Provider: AWS

**Comment by stgleb** [comment]
We don't  have a Delete key pair routine so far, I'll add one.
