### ISSUE TITLE
2.0 UI: App details page shows app name instead of repo name

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1172]
![Screen Shot 2018-12-07 at 1:31 PM](http://marker.screenshots.prod.s3.amazonaws.com/f7a2c956a21a45b982238bd6d0cc618d-1544189508853.png)
---
### More Info

**Reported by:** Joe Kane (joe@qbox.io)
**Source URL**: [http://localhost:4200/catalog/stable/details/aerospike](http://localhost:4200/catalog/stable/details/aerospike)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 971</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@hetmanchuk @gopherstein what should change here? should we switch display the correct repo name or switch it to app name?
