### ISSUE TITLE
2.0.1: UI - Machine Type not resetting after creating a cluster

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1185]
![Screen Shot 2018-12-08 at 12:41 AM](http://marker.screenshots.prod.s3.amazonaws.com/57d771ea3bb54679acea0d36c589a432-1544229664546.png)

**Summary:**
After spinning up a cluster and then going through the 'Create Cluster' steps, the AZ and Machinetype is still set to the previous cluster.

**Steps to Reproduce:** 
1. Create a cluster
2. Go to create a second cluster
3. When you get to the Machine configuration page check the machine type and az
**Expected Results:** 
These fields should be blank
**Actual Results:** 
The settings you chose for the previous cluster are still there

**Notes:**
If you choose the same region as the previous cluster, that az will still be shown.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.110</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1581 x 990</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by eldridgeh** [comment]
fixed in #1195
