### ISSUE TITLE
2.0: UI - Typo in dropdown

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1188]
![Screen Shot 2018-12-10 at 1:02 PM](http://marker.screenshots.prod.s3.amazonaws.com/c56c39c6b67649f2b386756297934d90-1544446927763.png)
---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/system/cloud-accounts/new](http://localhost:4200/system/cloud-accounts/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by eldridgeh** [comment]
fixed in #1195
