### ISSUE TITLE
2.0.1: UI - Title on provisioning page should be centered and line-height should be changed to 150%

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1199]
![Screen Shot 2018-12-11 at 6:58 AM](http://marker.screenshots.prod.s3.amazonaws.com/e34d020c77cb4deea75c93a0b92ae2be-1544511511156.png)
---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:8080/clusters/d1f4ecbf](http://localhost:8080/clusters/d1f4ecbf)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
Awesome, thanks man!
