### ISSUE TITLE
Get rid off hardcoded kube-dns IP

### ISSUE THREAD

**Issue by stgleb** [supergiant/control#1226]
Currently kube-dns contains hard coded ip addr in manifest file

https://github.com/supergiant/control/blob/master/templates/manifest.sh.tpl#L184 we need a bit smarter for doing that because cluster-ip range can be changed.

**Comment by saheienko** [comment]
Service range has been hardcoded too. 
https://github.com/supergiant/control/blob/master/templates/manifest.sh.tpl#L269
