### ISSUE TITLE
2.0.1: UI - fix line height or limit symbols in Cluster Details page

### ISSUE THREAD

**Issue by hetmanchuk** [supergiant/control#1289]
**Short Summary:**
![image](https://user-images.githubusercontent.com/11389252/52778191-15a18500-304e-11e9-9b0a-09b3c8a5080d.png)

**Expected Results:**
If parameter value is long, limit it with 3 dots or make another element under it dependent.

**Option 1:**
![image](https://user-images.githubusercontent.com/11389252/52778626-18e94080-304f-11e9-8c15-f045fa7701c5.png)

**Option 2:**
![image](https://user-images.githubusercontent.com/11389252/52778361-8b0d5580-304e-11e9-9253-f90f7cf1b3c4.png)

**Actual Results:**
Parameter value merges with underlying value.

**Dev Info:**
Latest Chrome on latest MacOS

**Comment by eldridgeh** [comment]
This is no longer happening.
