### ISSUE TITLE
Cluster configuration validation

### ISSUE THREAD

**Issue by stgleb** [supergiant/control#1313]
User must not be able to spin-up cluster without worker nodes, this should be checked on UI
that cluster must have at least one master and one worker node otherwise kubeadm provisioning will fail.

**Comment by eldridgeh** [comment]
@stgleb This is no longer happening.
When trying to create just a master or node you get the below error in the UI now:
```
Current machine configuration is invalid. Please check that each machine has a type, role, the quantity of masters is an odd number, and there is at least one node.
```
