### ISSUE TITLE
Can't delete cluster in DO

### ISSUE THREAD

**Issue by josephkane** [supergiant/control#1320]
To reproduce:
1. Spin up 1 master, 1 node cluster in DO, any region (I used 2gb machines for each)
2. After cluster is operational, delete it

SG logs will show:
```
DEBU[2019-03-01T12:35:11-06:00] Delete kube 2e0191aa 
DEBU[2019-03-01T12:35:11-06:00] start task from step #0 startIndex cleanUp 
INFO[2019-03-01T12:35:11-06:00] cleanUp
```
and hang forever

**Comment by stgleb** [comment]
Closed: #1321
