### ISSUE TITLE
EC2 metada API need to be available on k8s nodes & ProviderID need to be set

### ISSUE THREAD

**Issue by taaraora** [supergiant/control#1384]
**Short Summary:**
1. EC2 metadata API need to be available on worker nodes and master nodes. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
Especially ` "/aws/meta-data/instance-id"` and `"/aws/meta-data/instance-type"`
2. ProviderID need to be set on node.
3. `expose service` command doesn't work

**Steps to Reproduce:**
1. from nodes shell execute ` curl http://169.254.169.254/latest/meta-data/instance-id `
2. `kubectl describe nodes | grep ProviderID`
3. `kubectl expose service etcd-cluster-client --type=LoadBalancer --name=my-etcd -n weave`

**Expected Results:**
1. e. g. ```i-07a3ea5e4035a91b6```
2. e. g.
```
taaraora@qbox-t:~$ kubectl describe nodes | grep ProviderID
ProviderID:                  aws:///us-west-1b/i-002876f3a28678660
ProviderID:                  aws:///us-west-1b/i-07a3ea5e4035a91b6
ProviderID:                  aws:///us-west-1b/i-07820be558fbdebdb
ProviderID:                  aws:///us-west-1b/i-0fe0a2fd69c87f784
```
3. e. g. 
```
taaraora@qbox-t:/c/go-path/src/github.com/supergiant/conformity$ kubectl expose service etcd-cluster-client --type=LoadBalancer --name=my-etcd -n weave
service/my-etcd exposed
taaraora@qbox-t:/c/go-path/src/github.com/supergiant/conformity$ kubectl get svc -n weave
NAME                  TYPE           CLUSTER-IP     EXTERNAL-IP                                                               PORT(S)             AGE
etcd-cluster          ClusterIP      None           <none>                                                                    2379/TCP,2380/TCP   1d
etcd-cluster-client   ClusterIP      10.3.70.158    <none>                                                                    2379/TCP            1d
my-etcd               LoadBalancer   10.3.137.202   a7ad242ad61fc11e98661065a94252b0-2031200886.us-west-1.elb.amazonaws.com   2379:30881/TCP      4m
weave-scope-app       ClusterIP      10.3.8.68      <none>                                                                    80/TCP              41d
``` 

**Actual Results:**

**Dev Info:** (add links to log files)
1. Output of `go version`:
2. Commit hash or release tag used (`git log`):
3. Number of Masters and Nodes:
4. Cloud Provider:
5. Logs from `/tasks/{task_id}/logs/ws` UI/API endpoint for involved clusters:
6. Log files from `/tmp`, on the machine Control is running on (for example: `/tmp/314c2c2c-62b7-461b-8022-04dabeb0d19d.log`):

**Comment by saheienko** [comment]
Fixed with https://github.com/supergiant/control/pull/1386
