### ISSUE TITLE
2.0.1: Choosing a machine type not in order on DO cluster creation

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#791]
Summary of Issue:
When creating a DO cluster with 2.0, choosing a machine type is not in order.

Steps to Reproduce:
1. Begin creating a cluster in DO
2. When you get to the machine type
3. Click the drop down

Expected Results:
The drop down is ordered correctly.

Actual Results:
The machine types are not ordered correctly. 16gb is above 1gb.

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10 
2. SG latest commit hash or release tag: dddedff38267d34e16763fde1955ca4dec1cc5d7
3. Number of Masters and Nodes: Any
4. cloud provider: DO

**Comment by gopherstein** [comment]
Getting rid of this issue for now, as I think the machine type searchability feature should improve this functionality. We can come back to it is search is not enough.
