### ISSUE TITLE
2.0: API - AWS machine types show up twice

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#812]
![Screen Shot 2018-11-09 at 7:33 PM](http://marker.screenshots.prod.s3.amazonaws.com/9ad534dad9de4abb915cf12dbec2ea9a-1541791980055.png)
---
### More Info

**Reported by:** Joe Kane (joe@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 970</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
Looks like some other error may not be getting handled... and this is a result of a broken UI. When we test it, we cannot reliably reproduce it, and when we do produce it, a refresh seems to resolve it.

**Comment by josephkane** [comment]
I've been able to reproduce this in almost all regions. In addition, this is the http response from Postman: 
<img width="318" alt="screen shot 2018-11-09 at 2 08 17 pm" src="https://user-images.githubusercontent.com/18269936/48285774-4196e400-e429-11e8-8ad9-4ae971f7d441.png">

**Comment by eldridgeh** [comment]
@gopherstein  This is still an issue.

**Comment by gopherstein** [comment]
Duplicate: tracking in https://github.com/supergiant/control/issues/1004
