### ISSUE TITLE
2.0: API - Shutdown needs to be done under INFO

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#815]
Summary of Issue:
Shutting down Supergiant server with cntrl-c shows the shutdown as an ERROR.

Steps to Reproduce:
1. Start SG manually 
2. Stop the server with cntrl-c

Expected Results:
The server shuts down and the `http: Server closed ` falls under INFO

Actual Results:
The server shuts down and the `http: Server closed ` falls under ERROR

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10 
2. SG latest commit hash or release tag: c023d01e9abc7f91bd7da756056da4046f55207c
`^CINFO[2282] shutting down...                             
ERRO[2282] http: Server closed  `

**Comment by gopherstein** [comment]
This needs to be a warning. Not a fatal or error.

**Comment by gopherstein** [comment]
I feel like this is a little nitpicky, I am going to go ahead and close this for now, and we can make this change in a future patch if we choose.
