### ISSUE TITLE
2.0: UI - We need to be able to edit the name of an existing Cloud account.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#828]
![Screen Shot 2018-11-09 at 10:07 PM](http://marker.screenshots.prod.s3.amazonaws.com/76e1d60df6b74e21a69859cdaebdbd90-1541801260519.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/system/cloud-accounts/edit/DO](http://localhost:4200/system/cloud-accounts/edit/DO)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1610 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr></table>

**Comment by josephkane** [comment]
@gopherstein @eldridgeh this is impossible without altering how we store and reference cloud accounts in the db

**Comment by gopherstein** [comment]
I am making the executive decision to close this card, as current behaviour is desired. If a user changes a cloud account name, it could break anything using that account. (can of worms.)

https://imgflip.com/i/2nlbuq
