### ISSUE TITLE
2.0: build-image goal in Makefile has redundant `docker build` invocation

### ISSUE THREAD

**Issue by taaraora** [supergiant/control#835]
Summary of Issue:
[Makefile](https://github.com/supergiant/supergiant/blob/master/Makefile) builds image twice. 
```
build-image:
	docker build -t $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .
	docker build -t $(DOCKER_IMAGE_NAME):latest .
```

Expected Results:
It is possible just to tag image and do not build it twice.

```
build-image:
	docker build -t $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .
	docker tag $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) $(DOCKER_IMAGE_NAME):latest
```

Or such repetitive build added intentionally?

**Comment by gopherstein** [comment]
This is part of the install process.

**Comment by gopherstein** [comment]
This was resolved with release fixes.
