### ISSUE TITLE
2.0: UI - We need to forbid users from spinning up even number of masters

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#842]
![Screen Shot 2018-11-12 at 4:50 PM](http://marker.screenshots.prod.s3.amazonaws.com/b190fde5b50e409db89a8d341ebbfe61-1542041426767.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1334 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
I think this should only be made on the UI, so that a user can override with the API. 

I also think we might consider making it overridable in the UI...

**Comment by josephkane** [comment]
per war room discussion, this is part of a greater initiative to add some form of education to the provisioner wizard. Closing, will reopen if needed.
