### ISSUE TITLE
2.0.1: UI - APPs Store- Elasticsearch app in SG repo needs vetting

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#846]
Summary of Issue:
When deploying the elasticsearch app in the Supergiant vetted repo, the pods can not start due to a missing storage class.

Steps to Reproduce:
1. Deploy a cluster
2. Deploy the elasticsearch app form the SG vetted repo

Expected Results:
The elasticsearch app is deployed without issue.

Actual Results:
All pods are pending due to errors as is the pvc

Dev Info: (fill out and add links to log files)
1. `go version`: 1.10
2. SG latest commit hash or release tag: 300a006cafd9b09edb5da89aa14497f4326d1a3c
3. Number of Masters and Nodes: Any
4. cloud provider: DO

`  Warning  FailedScheduling  4m (x123 over 14m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)`

`Normal  FailedBinding  12s (x63 over 15m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set`

**Comment by gopherstein** [comment]
Removed the ES chart from the repo for now as this should belong to stable.
