### ISSUE TITLE
2.0: UI - App description contains info for the previously-selected app, not the currently selected one

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#848]
![Screen Shot 2018-11-12 at 7:04 PM](http://marker.screenshots.prod.s3.amazonaws.com/a398866011074707a4195170c2d52941-1542049498865.png)

Steps to reproduce:
1. Go to "/apps"
2. Select "Stable" repo
3. Choose any app
4. Go back to "Stable" repo
5. Choose a different app
6. Read the description and see that it is for the previously-selected app

---
### More Info

**Reported by:** Joe Kane (joe@qbox.io)
**Source URL**: [http://localhost:4200/apps/stable/details/bookstack](http://localhost:4200/apps/stable/details/bookstack)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 970</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@nikage

**Comment by gopherstein** [comment]
@josephkane Having trouble reproducing. Is this still happening?

**Comment by nikage** [comment]
fixed in . #1013
