### ISSUE TITLE
2.0.1: UI - Apps Store: fix header background and add background to each logo

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#854]
![Screen Shot 2018-11-13 at 3:02 PM](http://marker.screenshots.prod.s3.amazonaws.com/d473e995a4054732acf700c0ee4d2123-1542121341357.png)

**Summary:**
Header background must be filled with 90% black, now it's transparent / Add white circle on each logo background, same as in design

**Steps to Reproduce:** 
1. Go to Apps Store
2. Add minimum 1 repo

**Expected Results:** 
1. Header background is the same as in design
2. Logotypes of charts is presented the same as in design

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/apps/stable](http://localhost:4200/apps/stable)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@gopherstein @hetmanchuk can this be closed?
