### ISSUE TITLE
2.0 UI: Add node only returns machine types if the user has a cloud account named 'aws'

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#892]
![Screen Shot 2018-11-15 at 2:23 PM](http://marker.screenshots.prod.s3.amazonaws.com/4386505c4aaa4b459b77a7c9dbd62613-1542291783844.png)

In addition, it looks like we have no information on AWS clusters to denote the AZ that cluster is in, so the code for this feature just uses the first AZ in the array that comes back

---
### More Info

**Reported by:** Joe Kane (joe@qbox.io)
**Source URL**: [http://localhost:4200/clusters/4a86dbca/add-node](http://localhost:4200/clusters/4a86dbca/add-node)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 971</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
Looks like it might be hardcoded somewhere? To reproduce delete all AWS cloud providers, and add a cloud provider NOT named "aws"

**Comment by nikage** [comment]
@josephkane  Could not reproduce but just in case switched account type property source #1017

**Comment by gopherstein** [comment]
We are checking to see if this is still an issue.

**Comment by gopherstein** [comment]
This appears to be fixed. We will re-open of this issue comes back.
