### ISSUE TITLE
Align "Delete cluster" and "Cancel" to the center (since it can't be aligned by left side of table above)

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#905]
![Screen Shot 2018-11-16 at 2:37 PM](http://marker.screenshots.prod.s3.amazonaws.com/9f3b0f94492643fa8c2ad22698c6665e-1542379034709.png)
---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/clusters/de0576a2](http://localhost:4200/clusters/de0576a2)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
apology, I forgot to add "2.0: UI" to the title...

**Comment by josephkane** [comment]
@hetmanchuk can this be closed? I aligned the "delete" and "cancel" buttons with the table above it.
