### ISSUE TITLE
2.0.1: UI - AWS ebs optimized option needs to be added on completion of  #907

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#908]
![Screen Shot 2018-11-16 at 3:10 PM](http://marker.screenshots.prod.s3.amazonaws.com/64864020f6784fd384d531ac0c31d929-1542381024232.png)
---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1488 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@gopherstein @eldridgeh is this still necessary?

**Comment by eldridgeh** [comment]
Going to close this issue and will create a new one or reopen this once its needed.
