### ISSUE TITLE
2.0.1: UI - Align table columns & change trash icon

### ISSUE THREAD

**Issue by hetmanchuk** [supergiant/control#914]
<img width="1457" alt="slack_-_qbox_io" src="https://user-images.githubusercontent.com/11389252/48644232-abdff380-e9ea-11e8-8c2a-dfd8cf02d083.png">

**Summary:**
1. Align text in each column to the one vertical line (see screenshot)
2. Change trash icon to spec

**Steps to Reproduce:** 
1. Spin up 1 cluster with minimum 2 nodes
2. Go to cluster details page

**Expected Results:** 
1. All text in columns aligned to the one vertical line per each column (see screenshot)
2. Trash icon changed to the one from design spec

**Comment by hetmanchuk** [comment]
@josephkane

**Comment by josephkane** [comment]
@gopherstein @hetmanchuk can this be closed?
