### ISSUE TITLE
2.0: API - After rebooting the master, the etcd database can not be found.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#926]
**Short Summary:**
After rebooting the master, the master can not join the cluster due to the etcd db volume being stored in the /tmp directory.
**Steps to Reproduce:**
1. Spin up a cluster
2. ssh into the master and issue a reboot
**Expected Results:**
The box reboots and the cluster is working correctly
**Actual Results:**
The box reboots and the etcd database can not be found. It shows as started when checking systemctl status. However, nothing is happening. After restarting etcd with systemctl stop and restart, the etcd will not run.

Please see the attached screen shot to show that the volume is located at /tmp.
**Dev Info:** (add links to log files)
1. Output of `go version`: 1.10
2. Commit hash or release tag used (`git log`): bfa60ad35ccef78c4e51b19bd01eb2a1e06d2d3f
3. Number of Masters and Nodes: Any
4. Cloud Provider: DO and AWS
![screen shot 2018-11-19 at 10 32 31 am](https://user-images.githubusercontent.com/35240784/48721126-e1513080-ebe6-11e8-8c03-a8311f9462aa.png)

**Comment by gopherstein** [comment]
Fixed with: https://github.com/supergiant/control/pull/906
