### ISSUE TITLE
2.0: API - Nodes do not have roles set

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#932]
**Short Summary:**
After deploying a cluster and sshing into the master, running `kubectl get nodes` show that the master and nodes do not have roles set

**Expected Results:**
Masters should have a role of master and Nodes should have a role of node
**Actual Results:**
![screen shot 2018-11-20 at 9 46 59 am](https://user-images.githubusercontent.com/35240784/48785029-7c124380-eca9-11e8-9a8b-5138d65569a1.png)

**Dev Info:** (add links to log files)
1. Output of `go version`: 1.10
2. Commit hash or release tag used (`git log`): 470b93b5d6c4437bac88e00bd3c60f61415af244
3. Number of Masters and Nodes: Any
4. Cloud Provider: Any

**Comment by gopherstein** [comment]
Should we set a role? Masters should probably have a role. Should nodes?
