### ISSUE TITLE
2.0: UI - The Supergiant App repo should be able to be removed without breaking 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#933]
![Screen Shot 2018-11-20 at 3:51 PM](http://marker.screenshots.prod.s3.amazonaws.com/528081f5af72418daecf3055201ecd6a-1542729073218.png)
---
### More Info

Once the SG repo is removed, the Service Catalog is broken. 
Please see the attached pic:

<img width="1579" alt="screen shot 2018-11-20 at 9 53 12 am" src="https://user-images.githubusercontent.com/35240784/48785315-21c5b280-ecaa-11e8-8957-a0eff6baeaf5.png">

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by josephkane** [comment]
@gopherstein @eldridgeh should we allow the supergiant repo to be deleted? my first thought is no, but I'm obviously not sure.

**Comment by josephkane** [comment]
@nikage after talking with @gopherstein and @eldridgeh, we determined that users should not be able to remove the SG repo nor the Stable repo at this time

**Comment by nikage** [comment]
fixed in #1018
