### ISSUE TITLE
2.0: UI - There should be an animation showing progress when an app is deleted.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#934]
![Screen Shot 2018-11-20 at 3:55 PM](http://marker.screenshots.prod.s3.amazonaws.com/5c4a303a2793478ca9479046923a112f-1542729346427.png)
---
### More Info

There is not notification showing that an app is being deleted. After confirming, the app just dissapears.

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/dd9d1e3e](http://localhost:4200/clusters/dd9d1e3e)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@nikage, I've created animation. Trash icon animated from 100% to 0% opacity. 

Here is animation params:
![image](https://user-images.githubusercontent.com/11389252/49220846-fa749100-f3df-11e8-9191-06749cd36f7b.png) 

Link to prototype (animation): https://xd.adobe.com/view/1fe0bbb7-101c-4bc6-4e97-4178834c91ee-69d1/screen/c0ba1dd9-ca77-4531-ac76-26413b10057a/sg2-cluster-details-v2-5?fullscreen

Link to specs: https://xd.adobe.com/spec/3c5108bd-fd7f-467f-47f8-837ef0d07611-4a60/screen/c0ba1dd9-ca77-4531-ac76-26413b10057a/sg2-cluster-details-v2-5/
