### ISSUE TITLE
2.0: UI - User needs notification that they can click on task logs during provisioning.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#954]
![Screen Shot 2018-11-20 at 10:40 PM](http://marker.screenshots.prod.s3.amazonaws.com/590d0ae78f834825b93b9f3b25a10258-1542753623243.png)
---
### More Info

During user testing, two separate users asked what these icons were for. One user was fearful of clicking as he did not know what it would do.

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/102d9267](http://localhost:4200/clusters/102d9267)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
User test #2 had a similar observation. He did not know what to look at or where he could go during provisioning.  "My instinct is don't click away, but I really wanna click on stuff" He was afraid to click off the build and afraid of the icons as he didn't know what they meant.

**Comment by gopherstein** [comment]
Adding @hetmanchuk as the first responder on this, as it is more of a user flow issue. Once we have a plan we can re-assign to the frontend.

**Comment by hetmanchuk** [comment]
**Animation**: https://drive.google.com/open?id=1em_fRyix81jQIehIBKsCgjLYvEraD8aM

**Specs:** TH's text increases from 13px to 15px, ease out, 0.8 s, looped.

@gopherstein, please re-assign to @josephkane or @nikage

**Comment by gopherstein** [comment]
I am throwing another note on here... We need to figure out how to deploy progress on the tasks in a more obvious way. Possibly a progress on the task itself without it expanded.

**Comment by gopherstein** [comment]
a partial fix here with task column header. https://github.com/supergiant/control/pull/1061

**Comment by gopherstein** [comment]
I think there are a couple of things going on here. Yes, you should hide it until there is data, but... even when it is there. Every user so far has mentioned that they don't know what the button means, and/or if they can click on it or not.

**Comment by gopherstein** [comment]
@josephkane and I have discussed several options, like a tooltip, progress bar, etc.. on the main task to help provide more info. The tooltip might help the user know it is ok to click on the progress or logs buttons.

**Comment by josephkane** [comment]
@gopherstein @taras I think column headers will help a lot with informing users that there is something to click (already merged), but we also might consider changing the steps icon from the checkmarks to something like this: https://material.io/tools/icons/?icon=list&style=baseline. The checkmarks sort of look "actionable" to me, meaning "click me and I will DO something..." would I can understand making users unsure. A more benign icon might help that.

**Comment by taras** [comment]
@josephkane did you mean a different Taras?

**Comment by josephkane** [comment]
@taras, so sorry, I did. My bad!

**Comment by hetmanchuk** [comment]
> but we also might consider changing the steps icon from the checkmarks to something like this: https://material.io/tools/icons/?icon=list&style=baseline

@josephkane on the link there are all icon set, what icon exactly did you mean?

**Comment by josephkane** [comment]
@hetmanchuk 
![image](https://user-images.githubusercontent.com/18269936/49445742-3b7df400-f798-11e8-9f50-d7afe4286952.png)

**Comment by gopherstein** [comment]
We have several fixes for this in. I am closing this issue now for tracking. If we have continued user issues we can re-open if needed.
