### ISSUE TITLE
2.0: UI - User should be presented with 'getting started' section after creating a cluster

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#956]
**Short Summary:**
This section should contain items like:
1. ssh instructions
2. kubectl config (to run kubectl on local machine)
3. links to documentation
etc.

**Comment by gopherstein** [comment]
Adding @hetmanchuk as the first responder on this, as it is more of a user flow issue. Once we have a plan we can re-assign to the frontend.

**Comment by gopherstein** [comment]
A note from user test #2 on this one. The user was confused as to if the other SG tools were included automatically in the deploy. The getting started section could include info on deploying them? Also, should we allow a user to request them as part of provisioning? On the second question, we may need to discuss and make a feature issue.

**Comment by stgleb** [comment]
```
ssh root@<master-ip>

if AWS switch to ubuntu user
su ubuntu
sudo kubectl get nodes
else
kubectl get nodes
end
```

**Comment by josephkane** [comment]
cluster details "getting started" section:
1. here's how you ssh to your cluster
2. here's your kubectl config
3. click _here_ to deploy an app
4. various cURL commands
etc...

**Comment by hetmanchuk** [comment]
@josephkane, here is specs: https://xd.adobe.com/spec/3c5108bd-fd7f-467f-47f8-837ef0d07611-4a60/screen/06a79f07-0a14-4909-95f5-a8e07d828c78/sg2-cluster-details-v2/

**Comment by gopherstein** [comment]
closed with https://github.com/supergiant/control/pull/1061
