### ISSUE TITLE
2.0: UI - User should be provided with info when an app is installed.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#957]
When you deploy an app to a cluster, the user should be provided with the helm install return. 

The user should also be able to expand details for the app from the cluster details page and show app feedback, details, ports, etc.

**Comment by gopherstein** [comment]
Just like after cluster provisioning, the user needs an after app install call out.

**Comment by gopherstein** [comment]
Adding @hetmanchuk as the first responder on this, as it is more of a user flow issue. Once we have a plan we can re-assign to the frontend.

**Comment by gopherstein** [comment]
User testing  #1, #2 feedback: Need feedback about how to access my app.

**Comment by gopherstein** [comment]
This is a standard bit of data returned by helm after install. We just need to be displaying it to the user and saving it in a details tab for the deployed app.

**Comment by gopherstein** [comment]
User testing #2 feedback: 

* "I'm at the point where I'm like, I'm not sure where to go from here."
    * "I have a Docker image we would deploy to production. From here, I'm not sure if it's expected for users to leave UI and do that the way they traditionally would."

**Comment by josephkane** [comment]
@saheienko per war room discussion, we will need a GET endpoint for a release that returns release details and NOTES.txt

**Comment by gopherstein** [comment]
Looks like the backend is merged.
