### ISSUE TITLE
2.0: UI - Add repo and remove repo buttons need to be a single tile in Service Catalog

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#958]
![Screen Shot 2018-11-20 at 11:05 PM](http://marker.screenshots.prod.s3.amazonaws.com/afac62b39c33483cb17f3bd90f3ebdc2-1542755110589.png)
---
### More Info

We should remove the add/remove repo buttons  and make the very first tile in the Service Catalog be where the user clicks to add/remove a repo.

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by gopherstein** [comment]
Adding @hetmanchuk as the first responder on this, as it is more of a user flow issue. Once we have a plan we can re-assign to the frontend.

**Comment by gopherstein** [comment]
User testing #2 

* User remarked on repo selection buttons
    * "It seems like white is what's selected, but it's not, maybe it needs to be underlined"

**Comment by gopherstein** [comment]
The comment by user #2 would be solved by implementing this scheme.

**Comment by hetmanchuk** [comment]
@gopherstein @nikage This is incorrect implementation, here is design: https://xd.adobe.com/view/1fe0bbb7-101c-4bc6-4e97-4178834c91ee-69d1/screen/a0478d4a-7625-4596-a31d-8926e4c27a27/sg2-apps-list-sg?fullscreen

As you can see, active menu is pink and with 2 pixel underline, unselected is white and with dashed underline.

**Comment by hetmanchuk** [comment]
@gopherstein I think we can re-assign it to @nikage

**Comment by nikage** [comment]
fixed in #986
