### ISSUE TITLE
2.0: API - Insecure bind address for kubernetes api should be set to 127.0.0.1

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#965]
**Short Summary:**
It was found that the insecure bind address for the kube api server is being set to 0.0.0.0. This should instead be set to 127.0.0.1.

**Comment by gopherstein** [comment]
it would be worth it to ensure the etcd bind address is not open to the world too...

**Comment by gopherstein** [comment]
Fixed by #924
