### ISSUE TITLE
2.0: UI - Drop downs need to be removed if there are not any options to choose from

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#968]
![Screen Shot 2018-11-21 at 10:18 PM](http://marker.screenshots.prod.s3.amazonaws.com/5a73a9fc80ba43c7ac698456071d9eb0-1542838695366.png)

**Summary:**
During user testing the user recommended that we remove any dropdowns that did not have any options to choose from.

This should apply to anywhere in Control where drop downs are found but the text is hardcoded.

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/new](http://localhost:4200/clusters/new)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment]
@gopherstein @nikage @josephkane @eldridgeh 

Guys, a lot of words have been said about this issue before. Even when we were designing this UI Joe and I proposed not to show this drop-downs. But Yegor said that WE NEED this for the future when drop-downs will have more options and we will not have time to re-design it and re-implement it again.

So please think twice before changing it.

**Comment by nikage** [comment]
fixed #1032

**Comment by gopherstein** [comment]
Due to war room discussion, we will be not implementing this change. I will close the issue and we can re-open if minds change.
