### ISSUE TITLE
2.0: UI - 'Gathering usage data' needs to be more explicit.

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#972]
![Screen Shot 2018-11-21 at 10:36 PM](http://marker.screenshots.prod.s3.amazonaws.com/b2aaeb2ac43843cbacee2befc07a7979-1542839775183.png)

**Summary:**

During user testing, the user was confused on what 'Gathering usage data' was.

We need this to be more understandable. Something possibly like, 'Gathering your cluster's usage metrics'

---
### More Info

**Reported by:** eldridge henley (eldridge@qbox.io)
**Source URL**: [http://localhost:4200/clusters/13f7b92f](http://localhost:4200/clusters/13f7b92f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.77</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1623 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by egopher** [comment]
User data is currently not gathered.
